### ISSUE TITLE
Conflict with ggpubr

### ISSUE THREAD

**Issue by teddphil** [dewittpe/qwraps2#105]
Hi,

I am using _qwraps2_ for performing statistical analysis on my data and _ggplot2_ for visualisation. I am a little confused that _mean_sd_ seems not working when I load _ggpubr_. It reported that these parameters did not work
> denote_sd = 'paren',
>  digits = getOption("qwraps2_frmt_digits", 1

Currently it is working ok if I do not load _ggpubr_, but I am not sure if that is functioning as expected.
---

By submitting and issue I affirm:

- [x] Bug Report
    - [ ] I have included a minimal, self-contained, and reproducible example.  (Use of the R package [reprex](https://cran.r-project.org/package=reprex) is recommended for creating reproducible examples.)
    - [ ] Included session info via base R `sessionInfo()`, `sessioninfo::session_info()`, or `xfun::session_info()`.
    - [x] I have updated all packages.
    - [ ] I have tried the development version: `remotes::install_github("dewittpe/qwraps2")`

- [ ] Question
    - [ ] I have cross posted the question on Stack Overflow or RStudio Community
      and included a link to that posting within the post here.

- [ ] Feature Request
    - [ ] I have described the use case for the feature and explained why it
      would be useful.
    - [ ] I have provided a reprex sufficient to outline and inform the feature.

- [ ] I have formatted the issue via the Github Markdown syntax for to make the
  issue easy to read and examples easy to evaluate.

- [ ] I understand that my issue may be closed if I fail to provide the
  requested details.

**Comment by dewittpe** [comment]
The problem here is that ggpubr and qwraps2 both have a function `mean_sd` within their namespaces.  The solution is to explicitly use the namespace to call the version of the `mean_sd`.  That is, write `qwraps2::mean_sd` or `ggpubr::mean_sd` to specify which version of the function you want to use.  Note that the order the namespaces are loaded and attached to the session will change the order the function are used along the search tree.

**Comment by teddphil** [comment]
@dewittpe Many thanks!
