### ISSUE TITLE
"caption" argument in "print.qwraps2_summary_table"?

### ISSUE THREAD

**Issue by nrkoehler** [dewittpe/qwraps2#47]
Is there a way to integrate the 'caption' argument into the print method for 'qwraps2_summary_table' (like in knitr::kable()). It seems to be essential to reference tables. Thanks, Norbert

**Comment by dewittpe** [comment]
The `...` argument of the print method passes to `qwraps2::qable` which then passes to `knitr::kable`.  
So

```
print(obj, caption = "Example Caption", markup = "latex")
```
where `obj` is a `qwraps2_summary_table` object, then you should have the caption you are looking for in the output.

Do you have an example for where you'd like to see `print.qwraps2_summary_table` provide a caption?  It would help me if the example could show the expected behavior for a simple table generated by `knitr::kable`.

**Comment by nrkoehler** [comment]
Thanks very much! I've figured out how it works and added my example.
https://drive.google.com/open?id=15S9UyOdVCuOrpmJ4itt4oDboKayBS13f
