### ISSUE TITLE
summary_table treats literal underscore as latex markup

### ISSUE THREAD

**Issue by eipi10** [dewittpe/qwraps2#57]
I'm not sure if this is a bug, but it might be, so I thought I would report it here. [This question](https://community.rstudio.com/t/markdown-outputs-latex-code-to-pdf-but-no-table-what-could-be-wrong/13181) in the RStudio community forum reported an error when knitting the following `rmarkdown` document:

``````
---
title: "mtcars2"
output: pdf_document
---

```{r setup, include=FALSE}
library(qwraps2)
library(dplyr)
library(knitr)
```

```{r cars}
mtcars2 <-
  dplyr::mutate(mtcars,
                cyl_factor = factor(cyl,
                                    levels = c(6, 4, 8),
                                    labels = paste(c(6, 4, 8), "cylinders")),
                cyl_character = paste(cyl, "cylinders"))
our_summary1 <-
  list("Miles Per Gallon" =
         list("min" = ~ min(mpg),
              "max" = ~ max(mpg),
              "mean (sd)" = ~ qwraps2::mean_sd(mpg)),
       "Displacement" =
         list("min" = ~ min(disp),
              "max" = ~ max(disp),
              "mean (sd)" = ~ qwraps2::mean_sd(disp)),
       "Weight (1000 lbs)" =
         list("min" = ~ min(wt),
              "max" = ~ max(wt),
              "mean (sd)" = ~ qwraps2::mean_sd(wt)),
       "Forward Gears" =
         list("Three" = ~ qwraps2::n_perc0(gear == 3),
              "Four"  = ~ qwraps2::n_perc0(gear == 4),
              "Five"  = ~ qwraps2::n_perc0(gear == 5))
  )
```

```{r, results='asis'}
summary_table(group_by(mtcars2, cyl_factor), our_summary1)
```
``````
The error message is:
```
output file: mtcars.knit.md

! Missing $ inserted.
<inserted text> 
                $
l.165  & cyl_
             factor: 6 cylinders (N = 7) & cyl_factor: 4 cylinders (N = 11) ...

Error: Failed to compile mtcars.tex. See mtcars.log for more info.
Execution halted
```

The issue seems to be the underscore in the column name `cyl_factor`, which apparently gets interpreted as latex subscript markup rather than as a literal underscore.  The error can be avoided by escaping the underscore (`cyl\\_factor`) or by setting `options(qwraps2_markup = "markdown")`. The latter is the better solution, as it results in a nice looking table, while the former results in lots of gridlines and a table that runs off the right margin. (See the linked discussion in the RStudio forum for additional details.)

Other table creation packages, such as `kableExtra`, `xtable`, and `huxtable` correctly process the underscore as literal, so I wanted to point out the error with `table_summary` in case it's a bug.

**Comment by dewittpe** [comment]
@eipi10, thank you for the example and the posting the issue.

I'll keep thinking about this issue and how I might change how qwrap2 works.  Let me explain my conceptual design first.

In the example provided, I would have set `options(qwraps2_markup = "markdown")` because the document is an .Rmd file and thus I would want all my output from `summary_table` to be markdown.

The default, `options(qwraps2_markup = "latex")`, is what I expect to have when I work in a .Rnw file and thus want the output of `summary_table` to be LaTeX.

The escaping of the underscore becomes a bigger issue.  If, by default, all under scores are escaped then the markup $x_{1}$ would not render as desired.  Further escapement of `$`, the `@` symbol, etc., is more work than I really wanted to program for.  Look at the documentation `help(topic = "print.xtable", package = "xtable")` for an idea of the scope of options needed to support escapement of special characters.

My general approach to handling special characters in LaTeX is to do so explicitly.  This gives me the most control and is why in the passing of arguments from `qwraps2::summary_table` to `qwraps2::qable` to `knitr::kable` I have set `escape = !(markup = "latex")` in the arguments passed to `knitr::kable`.

I'm open to hearing your thoughts on the special character escapement.
