### ISSUE TITLE
qsummary() example

### ISSUE THREAD

**Issue by raheems** [dewittpe/qwraps2#66]
Now that the `tab_summary()` is being deprecated, and replaced by `qsummary()`, I was wondering how to update the following code. In particular, the option to be able to select the levels of a categorical variable using `[c( ) ]` is very useful.

```
mtcars2 <-
  dplyr::mutate(mtcars,
                cyl_factor = factor(cyl,
                                    levels = c(6, 4, 8),
                                    labels = paste(c(6, 4, 8), "cylinders")),
                cyl_character = paste(cyl, "cylinders"))
our_summary2 <-
  with(mtcars2,
       list("Miles Per Gallon" = tab_summary(mpg)[c(1, 4, 3)],
            "Displacement (default summary)" = tab_summary(disp),
            "Displacement" = c(tab_summary(disp)[c(1, 4, 3)],
                               "mean (95% CI)" = ~ frmtci(qwraps2::mean_ci(disp))),
            "Weight (1000 lbs)" = tab_summary(wt)[c(1, 4, 3)],
            "Forward Gears" = tab_summary(as.character(gear))
            ))
````

**Comment by dewittpe** [comment]
@raheems, `qsummary` does a better job of handling environments and that will
fundamentally change the programming style.


```r
library(qwraps2)  # version 0.3.0.9003
library(magrittr)
options(qwraps2_markup = "markdown")
```


The provided example:


```r
mtcars2 <-
  dplyr::mutate(mtcars,
                cyl_factor = factor(cyl,
                                    levels = c(6, 4, 8),
                                    labels = paste(c(6, 4, 8), "cylinders")),
                cyl_character = paste(cyl, "cylinders"))

our_summary2 <-
  with(mtcars2,
       list("Miles Per Gallon" = tab_summary(mpg)[c(1, 4, 3)],
            "Displacement (default summary)" = tab_summary(disp),
            "Displacement" = c(tab_summary(disp)[c(1, 4, 3)],
                               "mean (95% CI)" = ~ frmtci(qwraps2::mean_ci(disp))),
            "Weight (1000 lbs)" = tab_summary(wt)[c(1, 4, 3)],
            "Forward Gears" = tab_summary(as.character(gear))
            ))
```

```
## Warning: 'tab_summary' is deprecated.
## Use 'qsummary' instead.
## See help("Deprecated")

## Warning: 'tab_summary' is deprecated.
## Use 'qsummary' instead.
## See help("Deprecated")

## Warning: 'tab_summary' is deprecated.
## Use 'qsummary' instead.
## See help("Deprecated")

## Warning: 'tab_summary' is deprecated.
## Use 'qsummary' instead.
## See help("Deprecated")

## Warning: 'tab_summary' is deprecated.
## Use 'qsummary' instead.
## See help("Deprecated")
```




```r
summary_table(mtcars2, our_summary2)
```



|                                   |mtcars2 (N = 32)        |
|:----------------------------------|:-----------------------|
|**Miles Per Gallon**               |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |10.4                    |
|&nbsp;&nbsp; max                   |33.9                    |
|&nbsp;&nbsp; mean (sd)             |20.09 &plusmn; 6.03     |
|**Displacement (default summary)** |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |71.1                    |
|&nbsp;&nbsp; median (IQR)          |196.30 (120.83, 326.00) |
|&nbsp;&nbsp; mean (sd)             |230.72 &plusmn; 123.94  |
|&nbsp;&nbsp; max                   |472                     |
|**Displacement**                   |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |71.1                    |
|&nbsp;&nbsp; max                   |472                     |
|&nbsp;&nbsp; mean (sd)             |230.72 &plusmn; 123.94  |
|&nbsp;&nbsp; mean (95% CI)         |230.72 (187.78, 273.66) |
|**Weight (1000 lbs)**              |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |1.513                   |
|&nbsp;&nbsp; max                   |5.424                   |
|&nbsp;&nbsp; mean (sd)             |3.22 &plusmn; 0.98      |
|**Forward Gears**                  |&nbsp;&nbsp;            |
|&nbsp;&nbsp; 3                     |15 (47)                 |
|&nbsp;&nbsp; 4                     |12 (38)                 |
|&nbsp;&nbsp; 5                     |5 (16)                  |


The `tab_summary()` default for numeric values was to report the minimum,
median (IQR), mean (sd), and the maximum, in that order.  The `qsummary` has
the same defualts.  The following two call generate a similar object.


```r
suppressWarnings(with(mtcars2, list("Miles Per Gallon" = tab_summary(mpg))))
```

```
## $`Miles Per Gallon`
## $`Miles Per Gallon`$min
## ~min(mpg)
## <environment: 0x5579011ab7a0>
## 
## $`Miles Per Gallon`$`median (IQR)`
## ~qwraps2::median_iqr(mpg)
## <environment: 0x5579011ab7a0>
## 
## $`Miles Per Gallon`$`mean (sd)`
## ~qwraps2::mean_sd(mpg)
## <environment: 0x5579011ab7a0>
## 
## $`Miles Per Gallon`$max
## ~max(mpg)
## <environment: 0x5579011ab7a0>
```

```r
qsummary(mtcars2["mpg"]) %>% setNames(., "Miles Per Gallon")
```

```
## $`Miles Per Gallon`
## $`Miles Per Gallon`$minimum
## ~qwraps2::frmt(min(.data[["mpg"]]))
## 
## $`Miles Per Gallon`$`median (IQR)`
## ~qwraps2::median_iqr(.data[["mpg"]])
## 
## $`Miles Per Gallon`$`mean (sd)`
## ~qwraps2::mean_sd(.data[["mpg"]])
## 
## $`Miles Per Gallon`$maximum
## ~qwraps2::frmt(max(.data[["mpg"]]))
```


So, to get the min, max, mean (sd) you could do the following:


```r
suppressWarnings(with(mtcars2, list("Miles Per Gallon" = tab_summary(mpg)[c(1, 4, 3)])))
```

```
## $`Miles Per Gallon`
## $`Miles Per Gallon`$min
## ~min(mpg)
## <environment: 0x557901442aa0>
## 
## $`Miles Per Gallon`$max
## ~max(mpg)
## <environment: 0x557901442aa0>
## 
## $`Miles Per Gallon`$`mean (sd)`
## ~qwraps2::mean_sd(mpg)
## <environment: 0x557901442aa0>
```

```r
list("Miles Per Gallon" = qsummary(mtcars2["mpg"])[[1]][c(1, 4, 3)])
```

```
## $`Miles Per Gallon`
## $`Miles Per Gallon`$minimum
## ~qwraps2::frmt(min(.data[["mpg"]]))
## 
## $`Miles Per Gallon`$maximum
## ~qwraps2::frmt(max(.data[["mpg"]]))
## 
## $`Miles Per Gallon`$`mean (sd)`
## ~qwraps2::mean_sd(.data[["mpg"]])
```


To replicate the `our_summary2` object I would likely, in practice, write out
the explicit parts that I need.  I love having dynamic solutions, but I've
found time and time again with summary tables there is a limit to the level
of automation that can be made before something breaks.  Usually not within
a project, but certainly between projects.

That said, If we modify the `mtcars2$gear` to be factor we should be able to
recreate `our_summary2` from above as follows:


```r
mtcars2$gear %<>% factor(levels = c(3, 4, 5), labels = c("Three", "Four", "Five"))
```


only the needed columns to `qsummary`


```r
new_summary <-
  setNames(
           qsummary(mtcars2[c("mpg", "disp", "disp", "wt", "gear")])
           ,
           c("Miles Per Gallon",
             "Displacement (default summary)",
             "Displacement",
             "Weight (1000 lbs)",
             "Forward Gears"))
```


Remove the  median (IQR) rows and set the order of min, max, mean (sd) for
three of the row groups


```r
for (r in c("Miles Per Gallon", "Displacement", "Weight (1000 lbs)")) {
  new_summary[[r]] %<>% .[c(1, 4, 3)]
}
```


Add in the mean and CI for the second summary of displacement.  Note that
`disp.1` is the variable name hear because of the construction method.


```r
new_summary$`Displacement`$`mean (95% CI)` = ~ qwraps2::frmtci(qwraps2::mean_ci(disp.1))
new_summary
```

```
## $`Miles Per Gallon`
## $`Miles Per Gallon`$minimum
## ~qwraps2::frmt(min(.data[["mpg"]]))
## 
## $`Miles Per Gallon`$maximum
## ~qwraps2::frmt(max(.data[["mpg"]]))
## 
## $`Miles Per Gallon`$`mean (sd)`
## ~qwraps2::mean_sd(.data[["mpg"]])
## 
## 
## $`Displacement (default summary)`
## $`Displacement (default summary)`$minimum
## ~qwraps2::frmt(min(.data[["disp"]]))
## 
## $`Displacement (default summary)`$`median (IQR)`
## ~qwraps2::median_iqr(.data[["disp"]])
## 
## $`Displacement (default summary)`$`mean (sd)`
## ~qwraps2::mean_sd(.data[["disp"]])
## 
## $`Displacement (default summary)`$maximum
## ~qwraps2::frmt(max(.data[["disp"]]))
## 
## 
## $Displacement
## $Displacement$minimum
## ~qwraps2::frmt(min(.data[["disp.1"]]))
## 
## $Displacement$maximum
## ~qwraps2::frmt(max(.data[["disp.1"]]))
## 
## $Displacement$`mean (sd)`
## ~qwraps2::mean_sd(.data[["disp.1"]])
## 
## $Displacement$`mean (95% CI)`
## ~qwraps2::frmtci(qwraps2::mean_ci(disp.1))
## 
## 
## $`Weight (1000 lbs)`
## $`Weight (1000 lbs)`$minimum
## ~qwraps2::frmt(min(.data[["wt"]]))
## 
## $`Weight (1000 lbs)`$maximum
## ~qwraps2::frmt(max(.data[["wt"]]))
## 
## $`Weight (1000 lbs)`$`mean (sd)`
## ~qwraps2::mean_sd(.data[["wt"]])
## 
## 
## $`Forward Gears`
## $`Forward Gears`$Three
## ~qwraps2::n_perc(.data[["gear"]] == "Three", digits = 0, show_symbol = FALSE)
## 
## $`Forward Gears`$Four
## ~qwraps2::n_perc(.data[["gear"]] == "Four", digits = 0, show_symbol = FALSE)
## 
## $`Forward Gears`$Five
## ~qwraps2::n_perc(.data[["gear"]] == "Five", digits = 0, show_symbol = FALSE)
```


The resulting table is:


```r
summary_table(mtcars2[c("mpg", "disp", "disp", "wt", "gear")], new_summary)
```



|                                   |mtcars2[c("mpg", "disp", "disp", "wt", "gear")] (N = 32) |
|:----------------------------------|:--------------------------------------------------------|
|**Miles Per Gallon**               |&nbsp;&nbsp;                                             |
|&nbsp;&nbsp; minimum               |10.40                                                    |
|&nbsp;&nbsp; maximum               |33.90                                                    |
|&nbsp;&nbsp; mean (sd)             |20.09 &plusmn; 6.03                                      |
|**Displacement (default summary)** |&nbsp;&nbsp;                                             |
|&nbsp;&nbsp; minimum               |71.10                                                    |
|&nbsp;&nbsp; median (IQR)          |196.30 (120.83, 326.00)                                  |
|&nbsp;&nbsp; mean (sd)             |230.72 &plusmn; 123.94                                   |
|&nbsp;&nbsp; maximum               |472.00                                                   |
|**Displacement**                   |&nbsp;&nbsp;                                             |
|&nbsp;&nbsp; minimum               |71.10                                                    |
|&nbsp;&nbsp; maximum               |472.00                                                   |
|&nbsp;&nbsp; mean (sd)             |230.72 &plusmn; 123.94                                   |
|&nbsp;&nbsp; mean (95% CI)         |230.72 (187.78, 273.66)                                  |
|**Weight (1000 lbs)**              |&nbsp;&nbsp;                                             |
|&nbsp;&nbsp; minimum               |1.51                                                     |
|&nbsp;&nbsp; maximum               |5.42                                                     |
|&nbsp;&nbsp; mean (sd)             |3.22 &plusmn; 0.98                                       |
|**Forward Gears**                  |&nbsp;&nbsp;                                             |
|&nbsp;&nbsp; Three                 |15 (47)                                                  |
|&nbsp;&nbsp; Four                  |12 (38)                                                  |
|&nbsp;&nbsp; Five                  |5 (16)                                                   |


Again, I would, in practice, just write out each wanted row.  The PIs I work
with/for change their minds so often about the summaries they want it is
easier for me to have the rows explicit and comment them in or out as needed.



```r
new_summary2 <-
  list("Miles Per Gallon" = 
       list(
            "min" = ~ min(.data$mpg)
            ,
            "max" = ~ max(.data$mpg)
            ,
            "mean (sd)" = ~ mean_sd(.data$mpg)
            )
       , 
       "Displacement (default summary)" = 
       list(
            "min" = ~ min(.data$disp)
            ,
            "median (IQR)" = ~ median_iqr(.data$disp)
            ,
            "mean (sd)" = ~ mean_sd(.data$disp)
            ,
            "max" = ~ max(.data$disp)
            )
       ,
       "Displacement" = 
       list(
            "min" = ~ min(.data$disp)
            ,
            "max" = ~ max(.data$disp)
            ,
            "mean (sd)" = ~ mean_sd(.data$disp)
            ,
            "mean (95% CI)" = ~ frmtci(qwraps2::mean_ci(.data$disp))
            )
       ,
       "Weight (1000 lbs)" = 
       list(
            "min" = ~ min(.data$mpg)
            ,
            "max" = ~ max(.data$mpg)
            ,
            "mean (sd)" = ~ mean_sd(.data$mpg)
            )
       , 
       "Forward Gears" = 
       list(
            "Three" = ~ n_perc0(.data$gear == "Three")
            ,
            "Four" = ~ n_perc0(.data$gear == "Four")
            ,
            "Five" = ~ n_perc0(.data$gear == "Five")
            )
       )
```




```r
summary_table(mtcars2, new_summary2)
```



|                                   |mtcars2 (N = 32)        |
|:----------------------------------|:-----------------------|
|**Miles Per Gallon**               |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |10.4                    |
|&nbsp;&nbsp; max                   |33.9                    |
|&nbsp;&nbsp; mean (sd)             |20.09 &plusmn; 6.03     |
|**Displacement (default summary)** |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |71.1                    |
|&nbsp;&nbsp; median (IQR)          |196.30 (120.83, 326.00) |
|&nbsp;&nbsp; mean (sd)             |230.72 &plusmn; 123.94  |
|&nbsp;&nbsp; max                   |472                     |
|**Displacement**                   |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |71.1                    |
|&nbsp;&nbsp; max                   |472                     |
|&nbsp;&nbsp; mean (sd)             |230.72 &plusmn; 123.94  |
|&nbsp;&nbsp; mean (95% CI)         |230.72 (187.78, 273.66) |
|**Weight (1000 lbs)**              |&nbsp;&nbsp;            |
|&nbsp;&nbsp; min                   |10.4                    |
|&nbsp;&nbsp; max                   |33.9                    |
|&nbsp;&nbsp; mean (sd)             |20.09 &plusmn; 6.03     |
|**Forward Gears**                  |&nbsp;&nbsp;            |
|&nbsp;&nbsp; Three                 |15 (47)                 |
|&nbsp;&nbsp; Four                  |12 (38)                 |
|&nbsp;&nbsp; Five                  |5 (16)                  |

**Comment by dewittpe** [comment]
@raheems Be aware, there are changes coming to dplyr in version 0.8.0.  The current development version of dplyr is breaking `qwraps2::summary_table`.  There might be more changes coming.  See Issue #67

**Comment by raheems** [comment]
I appreciate your thorough example, and also about the upcoming issues with dplyr.
